version: '3'
services:
  detic-sample:
    environment:
      PYTHONPATH: src/
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'detic-sample'
    tty: true
    volumes:
      - .:/detic-sample/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ['gpu']
