version: '3'
services:
  detic-sample:
    environment:
      PYTHONPATH: src/
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'detic-sample'
    tty: true
    volumes:
      - .:/detic-sample/